from fastapi import APIRouter

from . import customers, carriers, facilities, quote_requests, quotes, shipments, tenders, tracking, documents, invoices, work_items, ai, analytics, emails, customs, loadboards, accounting, carrier_portal, customer_portal, automation, notifications, desks, approvals, automations, customer_contacts, customer_facilities, pricing_playbooks, carrier_compliance, document_inbox, billing, edi, rate_tables, communications, rbac, driver_app, search, tenant

router = APIRouter()

router.include_router(customers.router, prefix="/customers", tags=["customers"])
router.include_router(carriers.router, prefix="/carriers", tags=["carriers"])
router.include_router(facilities.router, prefix="/facilities", tags=["facilities"])
router.include_router(quote_requests.router, prefix="/quote-requests", tags=["quote-requests"])
router.include_router(quotes.router, prefix="/quotes", tags=["quotes"])
router.include_router(shipments.router, prefix="/shipments", tags=["shipments"])
router.include_router(tenders.router, prefix="/tenders", tags=["tenders"])
router.include_router(tracking.router, prefix="/tracking", tags=["tracking"])
router.include_router(documents.router, prefix="/documents", tags=["documents"])
router.include_router(invoices.router, prefix="/invoices", tags=["invoices"])
router.include_router(work_items.router, prefix="/work-items", tags=["work-items"])
router.include_router(ai.router, prefix="/ai", tags=["ai"])
router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
router.include_router(emails.router, prefix="/emails", tags=["emails"])
router.include_router(customs.router, prefix="/customs", tags=["customs"])
router.include_router(loadboards.router, prefix="/loadboards", tags=["loadboards"])
router.include_router(accounting.router, prefix="/accounting", tags=["accounting"])
router.include_router(carrier_portal.router, prefix="/carrier-portal", tags=["carrier-portal"])
router.include_router(customer_portal.router, prefix="/customer-portal", tags=["customer-portal"])
router.include_router(automation.router, prefix="/automation", tags=["automation"])
router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
router.include_router(desks.router, prefix="/desks", tags=["desks"])
router.include_router(approvals.router, prefix="/approvals", tags=["approvals"])
router.include_router(automations.router, prefix="/automations", tags=["automations"])
router.include_router(customer_contacts.router, prefix="/customers", tags=["customer-contacts"])
router.include_router(customer_facilities.router, prefix="/customers", tags=["customer-facilities"])
router.include_router(pricing_playbooks.router, prefix="/customers", tags=["pricing-playbooks"])
router.include_router(carrier_compliance.router, prefix="/carriers", tags=["carrier-compliance"])
router.include_router(document_inbox.router, prefix="/document-inbox", tags=["document-inbox"])
router.include_router(billing.router, prefix="/billing", tags=["billing"])
router.include_router(edi.router, prefix="/edi", tags=["edi"])
router.include_router(rate_tables.router, prefix="/rate-tables", tags=["rate-tables"])
router.include_router(communications.router, prefix="/communications", tags=["communications"])
router.include_router(rbac.router, prefix="/rbac", tags=["rbac"])
router.include_router(driver_app.router, prefix="/driver-app", tags=["driver-app"])
router.include_router(search.router, prefix="/search", tags=["search"])
router.include_router(tenant.router, prefix="/tenant", tags=["tenant"])
