export { LoginPage } from './LoginPage';
export { CalendarPage } from './CalendarPage';
export { ClientsPage } from './ClientsPage';
export { StaffPage } from './StaffPage';
export { ServicesPage } from './ServicesPage';
export { ReportsPage } from './ReportsPage';
export { SettingsPage } from './SettingsPage';
export { default as WaitlistPage } from './WaitlistPage';
export { default as PromotionsPage } from './PromotionsPage';
export { default as WebsiteBuilderPage } from './WebsiteBuilderPage';
